<?php

/**
 * File: events.php
 * Encoding: UTF-8
 * @package: plus-retail
 *
 * @Version: 1.0.0
 * @Since 16-okt-2012
 * @Author: Menno de Ridder <menno@sebsoft.nl>
 **/


defined('MOODLE_INTERNAL') || die();

/* List of events generated by the Drillster block, with the fields on the event object.

https://bitbucket.org/sebastianberm/plus-retail
block/highscore :)
blocks/highscore/db/events.php
blocks/highscore/class/EventHandler.php

drillster_unenrol_users
    ->component   = 'mod_quiz';
    ->attemptid   = // The id of the quiz attempt that was submitted.
    ->timefinish  = // The timestamp of when the attempt was submitted.
    ->userid      = // The user id that the attempt belongs to.
    ->submitterid = // The user id of the user who sumitted the attempt.
    ->quizid      = // The quiz id of the quiz the attempt belongs to.
    ->cmid        = // The course_module id of the quiz the attempt belongs to.
    ->courseid    = // The course id of the course the quiz belongs to.

*/
/*
$handlers = array(
    // Handle our own quiz_attempt_submitted event, as a way to send confirmation
    // messages asynchronously.
    'drillster_unenrol_users' => array (
        'handlerfile'     => '/blocks/drillster/class/EventHandler.php',
        'handlerfunction' => array('highscore_EventHandler'),
        'schedule'        => 'instant', //'cron',
        'internal'        => 1
    )
);*/